
import "../styles/globals.css"
import SideBar from "@/components/SideBar"
import { NextAuthProvider } from "@/components/SessionProvider"
import { getServerSession } from "next-auth"
import { authOptions } from "@/pages/api/auth/[...nextauth]"
import Login from "@/components/Login"
import CloseSideBar from "@/components/CloseSideBar"
import ClientProvider from "@/components/ClientProvider"
import MobileNav from "@/components/MobileNav"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <head>
        <body className="h-screen overflow-y-hidden">
          <NextAuthProvider session={session}>
            {
              !session ? <Login /> : (
                <div className="flex flex-col md:flex-row h-screen overflow-y-hidden">
                  <div className={`flex md:hidden`}>
                    <MobileNav />
                  </div>
                  <div className={`hidden md:block h-full overflow-y-hidden`}>
                    <SideBar />
                  </div>
                  <ClientProvider />
                  <div className="bg-[#343541] flex-1 text-white transition duration-300 z-10">{children}</div>
                </div>
              )
            }
          </NextAuthProvider>
        </body>
      </head>
    </html>
  )
}
